use crate::ast::Exit;
use crate::ast::Variable;
use crate::block::Block;
use crate::decl::ConstDecl;
use crate::decl::ProcDecl;
use crate::decl::VarDecl;
use crate::expression::BinOp;
use crate::expression::OddCondition;
use crate::expression::RelationalCondition;
use crate::io::Read;
use crate::io::Write;
use crate::io::WriteStr;
use crate::program::Program;
use crate::statement::AssignStmt;
use crate::statement::BeginStmt;
use crate::statement::CallStmt;
use crate::statement::IfStmt;
use crate::statement::WhileStatement;
use crate::types::Ident;
use crate::types::Number;
use crate::errors:: Pl0Result;

pub trait ASTVisitor {
    fn visit_ident(&mut self, ident: &Ident) -> Pl0Result<String>;
    fn visit_number(&mut self, number: &Number) -> Pl0Result<String>;
    fn visit_variable(&mut self, variable: &Variable) -> Pl0Result<String>;
    fn visit_binary_operation(&mut self, binary_operation: &BinOp) -> Pl0Result<String>;
    fn visit_while_statement(&mut self, while_statement: &WhileStatement) -> Pl0Result<()>;
    fn visit_condition(&mut self, condition: &OddCondition) -> Pl0Result<String>;
    fn visit_relational_condition(&mut self, condition: &RelationalCondition ) -> Pl0Result<String>;
    fn visit_call(&mut self, condition: &CallStmt) -> Pl0Result<()>;
    fn visit_assign(&mut self, expr: &AssignStmt) -> Pl0Result<()>;
    fn visit_begin(&mut self, expr: &BeginStmt) -> Pl0Result<()>;
    fn visit_if(&mut self, expr: &IfStmt) -> Pl0Result<()>;
    fn visit_write_int(&mut self, expr: &Write) -> Pl0Result<()>;
    fn visit_write_str(&mut self, expr: &WriteStr) -> Pl0Result<()>;
    fn visit_read_int(&mut self, expr: &Read) -> Pl0Result<()>;
    fn visit_exit(&mut self, expr: &Exit) -> Pl0Result<()>;
    fn visit_const(&mut self, expr: &ConstDecl) -> Pl0Result<()>;
    fn visit_var_decl(&mut self, expr: &VarDecl) -> Pl0Result<()>;
    fn visit_proc_decl(&mut self, expr: &ProcDecl) -> Pl0Result<()>;
    fn visit_block(&mut self, expr: &Block) -> Pl0Result<()>;
    fn visit_program(&mut self, expr: &Program) -> Pl0Result<()>;
}
